name: GitHub Actions Demo

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main

  schedule:
    - cron: '15 6 * * 0'

  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Output the event name
        run: echo "${{ github.event_name }}"

      - name: Output the current branch name
        run: echo "${{ github.ref_name }}"

      - name: List all files in the repository
        run: ls -la
